version: "3.9"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    container_name: elastic
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datavolume:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.2
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - elastic
    depends_on:
      - elastic
    ports:
      - 5601:5601

volumes:
  datavolume:
    driver: local

networks:
  elastic:
    driver: bridge
